version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "pip"
    directory: "/docs"
    schedule:
      interval: "daily"
    ignore:
      # sphinx-rtd-theme does not support the latest versions of docutils and
      # sphinx
      - dependency-name: "docutils"
      - dependency-name: "sphinx"
